models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return bool whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

controllers/CartController.php
<?php

namespace app\controllers;

use yii\web\Response;
use yii\web\Controller;

class CartController extends Controller
{
	/**
	 * @return bool
	 */
	public function actionAdd(): bool
	{
		if (\Yii::$app->request->post('id') !== null) {
			\Yii::$app->shopCart->addItem([\Yii::$app->request->post('id')]);

			return true;
		}

		return false;
	}

	/**
	 * @return mixed
	 */
	public function actionAll()
	{
		return \Yii::$app->shopCart->allItems;
	}

	/**
	 * @return bool
	 */
	public function actionRemove(): bool
	{
		if (\Yii::$app->request->post('id') !== null) {
			\Yii::$app->shopCart->rremoveItem(\Yii::$app->request->post('id'));

			return true;
		}

		return false;
	}

	/**
	 * @return mixed
	 */
	public function actionRemoveAll()
	{
		return \Yii::$app->shopCart->emptyShoppingCart();
	}

	/**
	 * @return mixed
	 */
	public function actionGetBasket()
	{
		return \Yii::$app->shopCart->basket();
	}

	/**
	 * @param $action
	 *
	 * @return bool
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction($action)
	{
		\Yii::$app->response->format = Response::FORMAT_JSON;
		return parent::beforeAction($action);
	}
}

controllers/CommentController.php
<?php

namespace app\controllers;


use app\service\ProductCommentService;
use yii\web\Controller;
use yii\data\ActiveDataProvider;

class CommentController extends Controller
{
	public function actionCreate()
	{
		$dataProvider = new ActiveDataProvider([
			'query' => \app\models\pucomment\Comment::find()->where(['parent_id' => 0]),
		]);

		if (\Yii::$app->request->isPjax) {
			$data = \Yii::$app->request->post();
			$comment = ProductCommentService::get();
			$comment->load($data);
			 $comment->save();
		}

		return \app\widgets\comment\Comment::widget(['dataProvider' => $dataProvider]);
	}
}

controllers/ProductController.php
<?php

namespace app\controllers;


use app\models\product\Product;
use app\service\ProductService;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class ProductController extends Controller
{
	/**
	 * @return string
	 */
	public function actionIndex(): string
	{
		$product = Product::find()->all();

		return $this->render('index', [
			'models' => $product
		]);
	}

	public function actionView($id)
	{
		$product = ProductService::get($id);

		$dataProvider = new ActiveDataProvider([
			'query' => \app\models\pucomment\Comment::find()->where(['parent_id' => 0, 'product_id' => $product->id]),
		]);

		return $this->render('view', [
			'product' => $product,
			'dataProvider' => $dataProvider,
		]);
	}
}

controllers/SignUpFormController.php
<?php

namespace app\controllers;


use app\models\user\form\SignUpForm;
use app\service\UserService;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;

class SignUpFormController extends  Controller
{
	/**
	 * @return array
	 */
	public function behaviors() :array
	{
		return [
			'access' => [
				'class' => AccessControl::class,
				'rules' => [
					[
						'actions' => ['index'],
						'allow' => true,
						'roles' => ['?'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'final-up' => ['get']
				],
			],
		];
	}

	/**
	 * @return string|\yii\web\Response
	 * @throws \yii\base\Exception
	 */
	public function actionIndex()
	{
		$signUpForm = UserService::getSignUpForm();

		/** @var SignUpForm $signUpForm */
		if ($signUpForm->load(\Yii::$app->request->post()) && $signUpForm->signUp()) {
			return $this->goHome();
		}

		return $this->render('index', [
			'model' => $signUpForm
		]);
	}

	public function actionFinalUp($code)
	{
		if (UserService::checkCode($code)) {
			return $this->redirect(Url::to(['profile/user/update', 'id' => \Yii::$app->user->identity->getId()]));
		}

		\Yii::$app->session->setFlash('badCode', 'This link is not valid');

		return $this->render('final-up');
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\user\form\LoginForm;
use app\widgets\comment\Comment;
use yii\data\ActiveDataProvider;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
	    $dataProvider = new ActiveDataProvider([
		    'query' => \app\models\pucomment\Comment::find()->where(['parent_id' => 0]),
	    ]);
        return $this->render('index', [
        	'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/comment/index.php
<?php

/* @var $this \yii\web\View */
/* @var $dataProvider \app\controllers\ActiveDataProvider */
?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
	        \app\widgets\lang\Lang::widget(),
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            ),

        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/product/index.php
<?php

/* @var $this \yii\web\View */


/* @var $models  */
?>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<?php foreach ($models as $model): ?>
			<div class="col-lg-4" style="border: black inset 1px; margin: 10px">
				<div class="col-lg-10">
					<div class="col-md-4">
						<?= \yii\helpers\Html::img('image/test2019-04-Mon-08-04-12.jpg', ['style' =>  'max-width: 100%']) ?>
					</div>
					<div class="col-md-12">
						Name: <?= $model->title ?>
					</div>
					<div class="col-md-12">
						Price: <?= $model->price ?>
						<?=  \app\widgets\cart\CartWidget::widget(['id' => $model->id])?>
					</div>
				</div>
				<div class="col-md-2">
					<?= \yii\helpers\Html::button('buy') ?>
				</div>
			</div>
			<?php endforeach; ?>
		</div>
	</div>
</div>

views/product/view.php
<?php

/* @var $this \yii\web\View */
/* @var $product \app\models\product\Product|null */
/* @var $dataProvider \app\controllers\ActiveDataProvider */

$model = \app\service\ProductCommentService::get();
?>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="col-lg-6" style="height: 100%; border-right: black solid 2px">
				<?php foreach ($product->gallery->images as $value): ?>
					<div class="col-lg-6" >
						<?= \yii\helpers\Html::img('/image/gallery/' . $value->path, ['class' => 'img-responsive'] ) ?>
					</div>
				<?php endforeach; ?>
			</div>
			<div class="col-lg-6">
				<ul>
					<li>
						title: <?= $product->title ?>
					</li>
					<li>
						description: <?= $product->description ?>
					</li>
					<li>
						price: <?= $product->price ?>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="row">
		<?php \yii\widgets\Pjax::begin(['enablePushState' => false]) ?>
		<?= \app\widgets\comment\Comment::widget(['dataProvider' => $dataProvider]) ?>
		<div class="container">
			<?php $form = \yii\widgets\ActiveForm::begin(['action' => \yii\helpers\Url::to(['comment/create'])]) ?>

			<?= $form->field($model, 'title')->textInput() ?>

			<?= $form->field($model, 'message')->textarea() ?>

			<?= $form->field($model, 'parent_id')->hiddenInput()->label(false) ?>
			<?= \yii\helpers\Html::submitButton('Submit')?>
			<?php  \yii\widgets\ActiveForm::end() ?>

		<?php \yii\widgets\Pjax::end() ?>
		</div>
	</div>


</div>

views/sign-up-form/final-up.php
<?php

/* @var $this \yii\web\View */
?>


<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<?php if( Yii::$app->session->hasFlash('badCode') ): ?>
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<?php echo Yii::$app->session->getFlash('badCode'); ?>
				</div>
			<?php endif;?>
		</div>
	</div>
</div>

views/sign-up-form/index.php
<?php

/* @var $this \yii\web\View */
/* @var $model \app\models\user\form\SignUpForm */
?>

<?php if( Yii::$app->session->hasFlash('errorSignUp') ): ?>
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo Yii::$app->session->getFlash('errorSignUp'); ?>
	</div>
<?php endif;?>
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="col-lg-6">
				<?php $form = \yii\widgets\ActiveForm::begin()?>

				<?= $form->field($model, 'name')->textInput() ?>

				<?= $form->field($model, 'surname')->textInput() ?>

				<?= $form->field($model, 'username')->textInput() ?>

				<?= $form->field($model, 'email')->textInput() ?>

				<?= $form->field($model, 'password_hash')->textInput()->passwordInput() ?>

				<?= $form->field($model, 'repeat_password')->textInput()->passwordInput() ?>

				<?= $form->field($model, 'country_id')->textInput()->dropDownList(\app\service\LocationService::countriesToArray()) ?>

				<?= $form->field($model, 'is_malling')->checkbox() ?>

				<?= $form->field($model, 'reCaptcha')->widget(
					\himiklab\yii2\recaptcha\ReCaptcha::className(),
					['siteKey' => '6Lcw55oUAAAAAEdXk-8X07rVkNq8VOXNkrkO6C_U']
				) ?>

				<?= \yii\helpers\Html::submitButton('Sign Up', ['class' => 'btn btn-success']) ?>

				<?php \yii\widgets\ActiveForm::end() ?>
			</div>
			<div class="col-lg-6">

			</div>
		</div>
	</div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">
        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\user\form\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>